"""initial migration

Revision ID: 9d933102e954
Revises: 
Create Date: 2025-03-04 13:20:24.042649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d933102e954'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_number', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('number_of_cycles', sa.Integer(), nullable=True),
    sa.Column('time_interval', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', name='teststatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests_job_number'), 'tests', ['job_number'], unique=True)
    op.create_table('banks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=True),
    sa.Column('bank_number', sa.Integer(), nullable=True),
    sa.Column('cell_type', sa.Enum('KPL', 'KPM', 'KPH', name='celltype'), nullable=True),
    sa.Column('cell_rate', sa.Float(), nullable=True),
    sa.Column('percentage_capacity', sa.Float(), nullable=True),
    sa.Column('discharge_current', sa.Float(), nullable=True),
    sa.Column('number_of_cells', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=True),
    sa.Column('cycle_number', sa.Integer(), nullable=True),
    sa.Column('reading_type', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=True),
    sa.Column('reading_number', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_ocv', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cell_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reading_id', sa.UUID(), nullable=True),
    sa.Column('cell_number', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cell_values')
    op.drop_table('readings')
    op.drop_table('cycles')
    op.drop_table('banks')
    op.drop_index(op.f('ix_tests_job_number'), table_name='tests')
    op.drop_table('tests')
    # ### end Alembic commands ### 