"""Initial migration

Revision ID: e047cb07716c
Revises: 
Create Date: 2025-03-21 01:20:37.919989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e047cb07716c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battery_banks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_battery_banks_id'), ['id'], unique=False)

    with op.batch_alter_table('reading_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_cycles_id'), ['id'], unique=False)

    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_readings_id'), ['id'], unique=False)

    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_sessions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_sessions_id'))

    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_readings_id'))

    with op.batch_alter_table('reading_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_cycles_id'))

    with op.batch_alter_table('battery_banks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_battery_banks_id'))

    # ### end Alembic commands ###
